import { cn } from "@/lib/utils";
import connectMongo from "@/service/mongo";
import { Hind_Siliguri, Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const hindSiliguri = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
export const metadata = {
  title: "Redcomrade | Blood donation management system",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const conn = await connectMongo();
  return (
    <html lang="en">
      <body className={cn(inter.className, hindSiliguri.className)}>
        {children}
        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8}
          containerClassName=""
          containerStyle={{}}
          toastOptions={{
            // Define default options
            className: "",
            duration: 5000,
            style: {
              background: "#363636",
              color: "#fff",
            },

            // Default options for specific types
            success: {
              duration: 3000,
              theme: {
                primary: "green",
                secondary: "black",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
