// const Skeleton = ({ image }) => (
//   <div className="flex  w-full h-full min-h-[6rem]">
//     <Image
//       src={image}
//       className="w-full h-full object-cover rounded-xl"
//       alt={blogs?.title}
//       width={100}
//       height={100}
//     />
//   </div>
// );

export const blogs = [
  {
    id: 1,
    title: "Blog 1",
    subTitle: "This is the first blog",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime quod perferendis nihil cupiditate aliquid qui exercitationem labore veritatis eaque nobis libero earum.",
    image: "/blogs/blogs-image-1.jpeg",
    date: "2024-01-01",
    author: "John Doe",
    category: "Category 1",
    // header: <Skeleton image="/blogs/blogs-image-1.jpeg" />,
    thumbnail: "/blogs/blogs-image-1.jpeg",
    // icon: <IconClipboardCopy className="h-4 w-4 text-neutral-500" />,
    tags: ["Tag 1", "Tag 2", "Tag 3"],
    isFeatured: true,
    isPublished: true,
    slug: "blog-2",
    views: 100,
    likes: 100,
    comments: 100,

    updatedAt: "2024-01-01",
  },
  {
    id: 2,
    title: "Blog 2",
    subTitle: "This is the second blog",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime quod perferendis nihil cupiditate aliquid qui exercitationem labore veritatis eaque nobis libero earum.",
    image: "/blogs/blogs-image-2.jpeg",
    date: "2024-01-01",
    author: "John Doe",
    category: "Category 1",
    // header: <Skeleton image="/blogs/blogs-image-2.jpeg" />,
    // icon: <IconClipboardCopy className="h-4 w-4 text-neutral-500" />,
    tags: ["Tag 1", "Tag 2", "Tag 3"],
    isFeatured: true,
    isPublished: true,
    slug: "blog-3",
    views: 100,
    likes: 100,
    comments: 100,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 3,
    title: "Blog 3",
    subTitle: "This is the third blog",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime quod perferendis nihil cupiditate aliquid qui exercitationem labore veritatis eaque nobis libero earum.",
    image: "/blogs/blogs-image-3.png",
    date: "2024-01-01",
    author: "John Doe",
    category: "Category 1",
    // header: <Skeleton image="/blogs/blogs-image-3.png" />,
    thumbnail: "/blogs/blogs-image-3.png",
    // icon: <IconClipboardCopy className="h-4 w-4 text-neutral-500" />,
    tags: ["Tag 1", "Tag 2", "Tag 3"],
    isFeatured: true,
    isPublished: true,
    slug: "blog-4",
    views: 100,
    likes: 100,
    comments: 100,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 4,
    title: "Blog 4",
    subTitle: "This is the fourth blog",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime quod perferendis nihil cupiditate aliquid qui exercitationem labore veritatis eaque nobis libero earum.",
    image: "/blogs/blogs-image-4.jpeg",
    date: "2024-01-01",
    author: "John Doe",
    category: "Category 1",
    // header: <Skeleton image="/blogs/blogs-image-4.jpeg" />,
    thumbnail: "/blogs/blogs-image-4.jpeg",
    // icon: <IconClipboardCopy className="h-4 w-4 text-neutral-500" />,
    tags: ["Tag 1", "Tag 2", "Tag 3"],
    isFeatured: true,
    isPublished: true,
    slug: "blog-4",
    views: 100,
    likes: 100,
    comments: 100,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 5,
    title: "Blog 5",
    subTitle: "This is the fifth blog",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime quod perferendis nihil cupiditate aliquid qui exercitationem labore veritatis eaque nobis libero earum.",
    image: "/blogs/blogs-image-5.jpeg",
    date: "2024-01-01",
    author: "John Doe",
    category: "Category 1",
    // header: <Skeleton image="/blogs/blogs-image-5.jpeg" />,
    thumbnail: "/blogs/blogs-image-5.jpeg",
    // icon: <IconClipboardCopy className="h-4 w-4 text-neutral-500" />,
    tags: ["Tag 1", "Tag 2", "Tag 3"],
    isFeatured: true,
    isPublished: true,
    slug: "blog-5",
    views: 100,
    likes: 100,
    comments: 100,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 6,
    title: "Blog 6",
    subTitle: "This is the sixth blog",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime quod perferendis nihil cupiditate aliquid qui exercitationem labore veritatis eaque nobis libero earum.",
    image: "/blogs/blogs-image-6.jpeg",
    date: "2024-01-01",
    author: "John Doe",
    category: "Category 1",
    // header: <Skeleton image="/blogs/blogs-image-6.jpeg" />,
    thumbnail: "/blogs/blogs-image-6.jpeg",
    // icon: <IconClipboardCopy className="h-4 w-4 text-neutral-500" />,
    tags: ["Tag 1", "Tag 2", "Tag 3"],
    isFeatured: true,
    isPublished: true,
    slug: "blog-6",
    views: 100,
    likes: 100,
    comments: 100,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: 7,
    title: "Blog 7",
    subTitle: "This is the seventh blog",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime quod perferendis nihil cupiditate aliquid qui exercitationem labore veritatis eaque nobis libero earum.",
    image: "/blogs/blogs-image-7.jpeg",
    date: "2024-01-01",
    author: "John Doe",
    category: "Category 1",
    // header: <Skeleton image="/blogs/blogs-image-7.jpeg" />,
    thumbnail: "/blogs/blogs-image-7.jpeg",
    // icon: <IconClipboardCopy className="h-4 w-4 text-neutral-500" />,
    tags: ["Tag 1", "Tag 2", "Tag 3"],
    isFeatured: true,
    isPublished: true,
    slug: "blog-7",
    views: 100,
    likes: 100,
    comments: 100,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const getBlogById = (slug) => {
  return blogs.find((blog) => blog.slug === slug);
};
